### ISSUE TITLE
Urban and rural classification

### ISSUE THREAD

**Issue by unbrother** [unbrother/traffic-major-minor#1]
The original model based the classification of roads as urban or rural from the settlement Ordnance Survey Meridian 2, the paper does not mention how (I assume it can be reverse-engineered from the .sql files), but I am not sure on how to do this with R.  I can't find the Meridian 2 files online but from the Strategi files, I found there's a layer named urban_region, which I could intersect with roads. I know this process would be very similar to the one that assigns AADT to roads but I'm unsure on how to do it.

@mem48
@Robinlovelace

**Comment by Robinlovelace** [comment]
Interesting, thanks for the update @unbrother and great work so far. I think intersecting the `urban_region` object with the roads is a good idea. You could use the function `st_join()` (as documented [here](https://geocompr.robinlovelace.net/spatial-operations.html#spatial-joining)) to add a new variable `urban`, with values being `TRUE` or `FALSE`.

**Comment by mem48** [comment]
There is an offical rural urban classification datasets here: https://www.ons.gov.uk/methodology/geography/geographicalproducts/ruralurbanclassifications/2011ruralurbanclassification if you download the Output Area dataset (these are the smallest areas) and join them onto the roads that should give you simislar results.

**Comment by mem48** [comment]
Also Ordnance Survey is a UK specific dataset so a method based on OpenStreetMap would be more internationalisable.
